import React, { useState } from 'react';

interface FAQItem {
  question: string;
  answer: string;
  isOpen: boolean;
}

const FAQ: React.FC = () => {
  const [faqs, setFaqs] = useState<FAQItem[]>([
    {
      question: 'What is an AI tourism content generator?',
      answer: 'An AI tourism content generator is a tool powered by artificial intelligence that automatically creates high-quality travel content based on information you provide, such as destination names, keywords, and preferences. TravelMind AI is a next-generation tool that not only generates content but also allows you to further customize it to truly match your brand style and needs.',
      isOpen: false
    },
    {
      question: 'What is the difference between AI-generated content and human-created content?',
      answer: 'AI generators can quickly create content drafts based on large amounts of data, while human creation requires more time but may be more creative. TravelMind AI combines the advantages of both: AI quickly generates initial drafts, then you can manually edit and customize, ensuring content is both efficient and unique, truly matching your brand tone.',
      isOpen: false
    },
    {
      question: 'How do I create travel content on TravelMind?',
      answer: 'Creating content on TravelMind is very simple: log into your account, select "Create New Content", enter destination information and keywords, choose the content type (such as destination introduction, itinerary planning, etc.), click generate, and then edit and refine the content as needed. The entire process is intuitive and efficient, allowing you to focus on creativity rather than tedious writing processes.',
      isOpen: false
    },
    {
      question: 'What types of content can I download?',
      answer: 'TravelMind supports multiple export formats: text documents (DOCX, PDF), image-text combined content, social media post formats, email marketing templates, and more. You can choose the most suitable format based on your usage scenario to ensure perfect presentation of content across platforms.',
      isOpen: false
    },
    {
      question: 'What resources are included besides text content?',
      answer: 'TravelMind provides not only text content but also: SEO keyword suggestions, content structure templates, audience analysis reports, competitor content analysis, seasonal content calendars, and more. These resources help you create more comprehensive and effective tourism marketing strategies.',
      isOpen: false
    },
    {
      question: 'How do I download my travel content?',
      answer: 'After generating and editing content, click the "Export" or "Download" button on the interface, select your desired file format, and the system will automatically package the content and provide a download link. Enterprise users can also push content directly to WordPress, CMS systems, or social media platforms.',
      isOpen: false
    },
    {
      question: 'Can I edit the content after generation?',
      answer: 'Absolutely! One of TravelMind\'s core advantages is full support for content editing. After generating content, you can use our editor to modify any part, adjust the tone, add personalized information, reorganize paragraphs, and even ask the AI to regenerate specific sections based on your feedback.',
      isOpen: false
    },
    {
      question: 'Can others copy my travel content?',
      answer: 'Content generated by TravelMind belongs to you. While we cannot completely prevent others from copying publicly published content, each user\'s generated content is unique, even if based on the same destination. Our system records your content creation history as proof of originality, and the enterprise version also provides content fingerprinting technology to help identify potential content plagiarism.',
      isOpen: false
    },
    {
      question: 'How can I create travel content for free?',
      answer: 'TravelMind offers a limited free plan where you can register an account and generate a certain amount of content each month. Free users can use basic features, but advanced editing, batch generation, and certain professional templates require upgrading to a paid plan. We also regularly host content creation challenges where participants can earn additional free generation credits.',
      isOpen: false
    },
    {
      question: 'What types of travel content can AI generate?',
      answer: 'TravelMind can generate various types of travel content: destination introductions, itinerary planning, attraction descriptions, travel tips, food guides, accommodation reviews, seasonal travel suggestions, featured experience recommendations, cultural background introductions, and more. Our AI is trained with professional tourism knowledge to create content that is both informative and engaging.',
      isOpen: false
    },
    {
      question: 'Why choose TravelMind over other content tools?',
      answer: 'TravelMind is built specifically for the tourism industry. Compared to general AI tools, we provide: tourism expertise, industry-specific templates, destination databases, tourism marketing best practices, multilingual localization support, tourism SEO optimization, and more. We understand the unique needs of travel content and help you create professional and attractive content that improves conversion rates and user engagement.',
      isOpen: false
    },
    {
      question: 'Can I use the generated content on social media?',
      answer: 'Absolutely! Content generated by TravelMind can be fully used on social media. We even provide dedicated social media templates optimized for different platforms (such as Instagram, Facebook, Twitter, etc.) in terms of content length and style. Enterprise users can also push content directly from the platform to social media accounts and receive posting suggestions and best time analysis.',
      isOpen: false
    },
    {
      question: 'Can I print the generated content on merchandise?',
      answer: 'Yes! You can print your content on over 200 products, including clothing, home goods, and lifestyle accessories. After creating free content, simply click "Merchandise" in the dashboard menu, select your favorite products, customize the design, and we will ship directly to you. Enterprise users can also get bulk order discounts and brand customization options.',
      isOpen: false
    },
    {
      question: 'What should I avoid when creating travel content?',
      answer: 'When creating travel content, you should avoid: overusing marketing terminology, ignoring cultural sensitivity, providing outdated information, lacking specific details, ignoring target audience needs, and making content too generic. TravelMind\'s AI assistant automatically flags these potential issues and provides improvement suggestions to help you create professional and attractive travel content.',
      isOpen: false
    }
  ]);

  const toggleFAQ = (index: number) => {
    setFaqs(faqs.map((faq, i) => {
      if (i === index) {
        return { ...faq, isOpen: !faq.isOpen };
      }
      return faq;
    }));
  };

  return (
    <section id="faq" className="py-20 bg-white">
      <div className="container mx-auto px-4 md:px-6">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <h1 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
            TravelMind AI Frequently Asked Questions
          </h1>
          <p className="text-lg text-gray-600">
            Learn how to use our AI tourism content generation tool to enhance your tourism marketing strategy
          </p>
        </div>

        <div className="max-w-4xl mx-auto">
          {faqs.map((faq, index) => (
            <div key={index} className="mb-4 border-b border-gray-200 pb-4">
              <button
                className="flex justify-between items-center w-full text-left font-medium text-gray-900 focus:outline-none"
                onClick={() => toggleFAQ(index)}
              >
                <span className="text-lg">{faq.question}</span>
                <svg
                  className={`w-6 h-6 transform ${faq.isOpen ? 'rotate-180' : ''} transition-transform`}
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                </svg>
              </button>
              {faq.isOpen && (
                <div className="mt-4 text-gray-600">
                  <p>{faq.answer}</p>
                </div>
              )}
            </div>
          ))}
        </div>

        <div className="text-center mt-16">
          <h2 className="text-2xl font-bold text-gray-900 mb-6">Start Using Our Tourism Content Generator</h2>
          <a
            href="#demo"
            className="inline-flex items-center px-6 py-3 bg-primary-600 hover:bg-primary-700 text-white font-medium rounded-lg transition-colors"
          >
            Try For Free
          </a>
        </div>
      </div>
    </section>
  );
};

export default FAQ;